name: Build and Push Docker Image

on:  
  push:
    branches:
      - main   
    paths:
      - 'basic-python-app/**'
      
  workflow_dispatch: 

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Generate Timestamp Tag
      id: vars
      run: |
        TIMESTAMP=$(date +%Y%m%d%H%M%S)  
        echo "TAG=$TIMESTAMP" >> $GITHUB_ENV

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image with Timestamp and Latest Tag
      run: |
        cd basic-python-app
        docker build -t ${{ secrets.DOCKER_USERNAME }}/flask-demo:${TAG} .
        docker tag ${{ secrets.DOCKER_USERNAME }}/flask-demo:${TAG} ${{ secrets.DOCKER_USERNAME }}/flask-demo:latest

    - name: Push to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/flask-demo:${TAG}
        
